default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres
  username: postgres@riverside-postgres-server
  password: <%= ENV["REACT_APP_DATABASE_PASSWORD"] %>
  host: riverside-postgres-server.postgres.database.azure.com
  port: 5432
  sslmode: require

test:
  <<: *default
  database: postgres
  username: postgres@riverside-postgres-server
  password: <%= ENV["REACT_APP_DATABASE_PASSWORD"] %>
  host: riverside-postgres-server.postgres.database.azure.com
  port: 5432
  sslmode: require

production:
  <<: *default
  database: postgres
  username: postgres@riverside-postgres-server
  password: <%= ENV["REACT_APP_DATABASE_PASSWORD"] %>
  host: riverside-postgres-server.postgres.database.azure.com
  port: 5432
  sslmode: require
